[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["Alex Williams <hughaw64@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
msolve = "0.2"

[profile.release]
opt-level = 3
lto = true
debug = true
